export const aboutContent = {
  section: {
    code: '// 02',
    title: 'O mnie',
    kicker: '// transmisja osobista',
  },
  profile: {
    imageAlt: 'Krzysztof',
    role: '// dev & builder · krk',
    name: 'Krzysztof Obarzanek',
    bio: 'Jestem pasjonatem technologii, który kocha doradzać w doborze sprzętu, składać komputery i tworzyć strony internetowe. Moja pasja do technologii napędza mnie do nieustannego doskonalenia swoich umiejętności i tworzenia rozwiązań, które łączą innowację z praktycznością.',
    btnKontakt: 'Kontakt',
  },
  tech: {
    code: '// tech',
    title: 'Technologie',
    kicker: 'Narzędzia, z których korzystam w pracy',
  },
  technologies: [
    [
      'Frontend',
      [
        'HTML5',
        'CSS3',
        'JavaScript',
        'TypeScript',
        'React',
        'Next.js',
        'Astro',
        'TailwindCSS',
        'shadcn/ui',
        'SCSS',
        'TanStack',
        'Framer Motion',
        'Zustand',
        'Vite',
        'Recharts',
        'react-hook-form',
      ],
    ],
    ['Mobile', ['React Native', 'Expo', 'Telegram Mini Apps', 'NativeWind']],
    [
      'Backend',
      [
        'Node.js',
        'NestJS',
        'Express',
        'Swagger',
        'JWT',
        'tRPC',
        'Zod',
        'NextAuth',
        'Stripe',
        'Resend',
        'Cloudinary',
        'UploadThing',
      ],
    ],
    [
      'Bazy',
      [
        'PostgreSQL',
        'MongoDB',
        'Prisma',
        'Supabase',
        'Firebase',
        'Redis',
        'SQLite',
        'Mongoose',
        'Neon',
      ],
    ],
    ['Web3', ['Ethers.js', 'Web3']],
    [
      'Testy',
      [
        'Jest',
        'Vitest',
        'Cypress',
        'Supertest',
        'React Testing Library',
        'Playwright',
      ],
    ],
    [
      'DevOps',
      [
        'Git',
        'Docker',
        'Grafana',
        'Prometheus',
        'GitHub Actions',
        'Vercel',
        'Railway',
        'Render',
        'Netlify',
      ],
    ],
    [
      'Edytory',
      [
        'Codex',
        'Claude Code',
        'Cursor',
        'GitHub Copilot',
        'VS Code',
        'Neovim',
        'WebStorm',
      ],
    ],
  ] as [string, string[]][],
} as const;
